version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=max
      # MONGO_INITDB_ROOT_USERNAME : max
      # MONGO_INITDB_ROOT_PASSWORD : secret
    env_file:
      - ./env/mongo.env
    # docker compose create his one network but we can add extra network 
    # networks:
      # - goals-net 
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    

volumes:
  data:
  logs:



# docker-compose up to excute this file 
# docker-compose up -d run on ditathced mod 
# docker-compose down
# docker-compose -v to remove data volume 